#!/usr/bin/env bash
# ============================================================
#  AgentGPT Bridge — Linux deployment script
#
#  Run ON the Linux GPU server from a repo checkout:
#
#    cd /path/to/Native-Mind-GPT
#    ./apps/bridge/deploy-linux.sh
#
#  Options (env vars):
#    INSTALL_DIR   deployment root        (default: /bridge-mcp)
#    SKIP_SYSTEMD  set to 1 to skip writing the systemd unit
#
#  What it does:
#    1. Syncs apps/bridge into $INSTALL_DIR
#    2. Installs uv if missing
#    3. Creates $INSTALL_DIR/.venv and installs deps (incl. mcp)
#    4. Writes $INSTALL_DIR/.env with a generated bridge token
#       (never overwrites an existing .env / token)
#    5. Writes a systemd unit (agentgpt-bridge.service) and prints
#       the exact enable/start commands
#    6. Prints the bridge URL, /mcp endpoint, and token so you can
#       register the host in the desktop app (Settings -> Remote Hosts)
# ============================================================
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/bridge-mcp}"
SKIP_SYSTEMD="${SKIP_SYSTEMD:-0}"
SERVICE_NAME="agentgpt-bridge.service"

# ---- locate the bridge source (this script lives in apps/bridge/) ---------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BRIDGE_SRC="$SCRIPT_DIR"

echo "==> Deploying bridge from $BRIDGE_SRC to $INSTALL_DIR"

# ---- 1. sync source --------------------------------------------------------
mkdir -p "$INSTALL_DIR"
if command -v rsync &>/dev/null; then
    rsync -a --delete \
        --exclude '.venv' \
        --exclude '__pycache__' \
        --exclude '.pytest_cache' \
        --exclude '.ruff_cache' \
        --exclude '.env' \
        "$BRIDGE_SRC/" "$INSTALL_DIR/"
else
    echo "    (rsync not found, falling back to tar)"
    ( cd "$BRIDGE_SRC" && tar cf - \
        --exclude='./.venv' \
        --exclude='./.env' \
        --exclude='./.pytest_cache' \
        --exclude='./.ruff_cache' \
        --exclude='*/__pycache__' \
        . ) | ( cd "$INSTALL_DIR" && tar xf - )
fi

# ---- 2. install uv if missing ----------------------------------------------
if ! command -v uv &>/dev/null; then
    echo "==> Installing uv"
    curl -LsSf https://astral.sh/uv/install.sh | sh
    # The installer drops uv into ~/.local/bin or ~/.cargo/bin.
    export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
fi
command -v uv &>/dev/null || { echo "ERROR: uv installation failed"; exit 1; }

# ---- 3. venv + dependencies -------------------------------------------------
echo "==> Installing dependencies into $INSTALL_DIR/.venv"
cd "$INSTALL_DIR"
uv sync

# ---- 4. .env with bridge token ----------------------------------------------
ENV_FILE="$INSTALL_DIR/.env"
if [[ -f "$ENV_FILE" ]]; then
    echo "==> Keeping existing $ENV_FILE (token NOT overwritten)"
else
    TOKEN="$(uv run --project "$INSTALL_DIR" python -c "import secrets; print(secrets.token_hex(32))")"
    cat > "$ENV_FILE" <<EOF
# AgentGPT Bridge environment — generated by deploy-linux.sh
# Register this token in the desktop app (Settings -> Remote Hosts).
AGENTGPT_BRIDGE_TOKEN=$TOKEN
AGENTGPT_BRIDGE_HOST=0.0.0.0
AGENTGPT_BRIDGE_PORT=8443
EOF
    chmod 600 "$ENV_FILE"
    echo "==> Wrote $ENV_FILE with a fresh token"
fi
# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a
BRIDGE_TOKEN="$AGENTGPT_BRIDGE_TOKEN"
BRIDGE_HOST="${AGENTGPT_BRIDGE_HOST:-0.0.0.0}"
BRIDGE_PORT="${AGENTGPT_BRIDGE_PORT:-8443}"

# ---- 5. systemd unit ----------------------------------------------------------
UNIT_PATH="/etc/systemd/system/$SERVICE_NAME"
if [[ "$SKIP_SYSTEMD" != "1" ]]; then
    UNIT_CONTENT="[Unit]
Description=AgentGPT Bridge (remote GPU workload host)
After=network.target

[Service]
Type=simple
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$ENV_FILE
ExecStart=$INSTALL_DIR/.venv/bin/python -m agentgpt_bridge --host \${AGENTGPT_BRIDGE_HOST} --port \${AGENTGPT_BRIDGE_PORT}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
"
    if [[ $EUID -eq 0 ]]; then
        printf '%s\n' "$UNIT_CONTENT" > "$UNIT_PATH"
        systemctl daemon-reload
        echo "==> Wrote systemd unit $UNIT_PATH"
    elif command -v sudo &>/dev/null && sudo -n true 2>/dev/null; then
        printf '%s\n' "$UNIT_CONTENT" | sudo tee "$UNIT_PATH" >/dev/null
        sudo systemctl daemon-reload
        echo "==> Wrote systemd unit $UNIT_PATH (via sudo)"
    else
        # No root: drop the unit next to the install for manual setup.
        printf '%s\n' "$UNIT_CONTENT" > "$INSTALL_DIR/$SERVICE_NAME"
        echo "==> No root privileges; wrote unit template to $INSTALL_DIR/$SERVICE_NAME"
    fi
fi

# ---- 6. summary ----------------------------------------------------------------
DISPLAY_HOST="$BRIDGE_HOST"
if [[ "$DISPLAY_HOST" == "0.0.0.0" || "$DISPLAY_HOST" == "::" ]]; then
    DISPLAY_HOST="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
    DISPLAY_HOST="${DISPLAY_HOST:-<this-host>}"
fi

cat <<EOF

============================================================
  Bridge deployed to $INSTALL_DIR

  Bridge URL:    http://$DISPLAY_HOST:$BRIDGE_PORT
  MCP endpoint:  http://$DISPLAY_HOST:$BRIDGE_PORT/mcp
  Health check:  http://$DISPLAY_HOST:$BRIDGE_PORT/health
  Token:         $BRIDGE_TOKEN

  Register this host in the desktop app:
    Settings -> Remote Hosts -> Add
    URL:   http://$DISPLAY_HOST:$BRIDGE_PORT
    Token: (above)

  To enable and start the service (needs root):
    sudo systemctl enable $SERVICE_NAME
    sudo systemctl start $SERVICE_NAME
    sudo systemctl status $SERVICE_NAME

  Or run in the foreground:
    cd $INSTALL_DIR && ./run-bridge.sh
============================================================
EOF
