"""Workload manager: registers workloads, enforces lifecycle, runs idle timers.

The manager owns all workloads and runs a background task that checks for idle
timeouts: soft idle (release VRAM) and hard idle (stop process). It also
provides a simple asset-token store so generated bytes can be fetched shortly
after a job completes.
"""

from __future__ import annotations

import asyncio
import logging
import time
import uuid
from typing import Any

from .workloads.base import JobResult, Workload, WorkloadInfo, WorkloadState

logger = logging.getLogger(__name__)

# How often the idle-check loop runs.
IDLE_CHECK_INTERVAL = 30.0  # seconds

# Asset tokens expire after this long (clients should fetch promptly).
ASSET_TOKEN_TTL = 600.0  # 10 minutes


class WorkloadManager:
    """Owns workloads and their lifecycle. Thread-safe via asyncio (single loop)."""

    def __init__(self) -> None:
        self._workloads: dict[str, Workload] = {}
        self._assets: dict[str, _StoredAsset] = {}
        self._idle_task: asyncio.Task[None] | None = None
        self._running = False

    # ---- registration ----

    def register(self, workload: Workload) -> None:
        """Register a workload by its workload_id."""
        self._workloads[workload.workload_id] = workload
        logger.info("registered workload: %s", workload.workload_id)

    def get(self, workload_id: str) -> Workload | None:
        return self._workloads.get(workload_id)

    def list(self) -> list[Workload]:
        return list(self._workloads.values())

    def infos(self) -> list[WorkloadInfo]:
        return [w.info() for w in self._workloads.values()]

    # ---- lifecycle ----

    async def ensure_started(self, workload_id: str) -> Workload:
        """Ensure a workload is started (start if stopped, wait if starting)."""
        wl = self._require(workload_id)
        if wl.state == WorkloadState.STOPPED:
            logger.info("starting workload %s on demand", workload_id)
            await wl.start()
        elif wl.state == WorkloadState.STARTING:
            logger.info("waiting for workload %s to become ready", workload_id)
            while wl.state == WorkloadState.STARTING and self._running:
                await asyncio.sleep(0.1)
        return wl

    async def stop(self, workload_id: str) -> None:
        wl = self._require(workload_id)
        await wl.stop()

    async def submit_job(self, workload_id: str, job: dict[str, Any]) -> JobResult:
        """Ensure the workload is started, then submit the job."""
        wl = await self.ensure_started(workload_id)
        result = await wl.submit_job(job)
        # Store outputs for later retrieval by asset_token.
        for output in result.outputs:
            token = output.get("asset_token") or str(uuid.uuid4())
            self._assets[token] = _StoredAsset(
                bytes=output.get("bytes", b""),
                mime_type=output.get("mime_type", "application/octet-stream"),
                created_at=time.monotonic(),
            )
        return result

    def get_asset(self, token: str) -> tuple[bytes, str] | None:
        """Fetch stored asset bytes by token. Returns None if expired/missing."""
        asset = self._assets.get(token)
        if asset is None:
            return None
        if time.monotonic() - asset.created_at > ASSET_TOKEN_TTL:
            del self._assets[token]
            return None
        return (asset.bytes, asset.mime_type)

    # ---- idle management ----

    def start_idle_loop(self) -> None:
        """Start the background idle-check task."""
        if self._idle_task is not None:
            return
        self._running = True
        self._idle_task = asyncio.create_task(self._idle_loop())

    async def stop_idle_loop(self) -> None:
        """Stop the background idle-check task."""
        self._running = False
        if self._idle_task is not None:
            self._idle_task.cancel()
            try:
                await self._idle_task
            except asyncio.CancelledError:
                pass
            self._idle_task = None

    async def _idle_loop(self) -> None:
        """Periodically check each workload for idle timeouts."""
        while self._running:
            try:
                await asyncio.sleep(IDLE_CHECK_INTERVAL)
                for wl in self._workloads.values():
                    await self._check_idle(wl)
            except asyncio.CancelledError:
                break
            except Exception:
                logger.exception("idle loop error")

    async def _check_idle(self, wl: Workload) -> None:
        """Apply soft/hard idle policy to a workload."""
        if wl.state not in (WorkloadState.READY, WorkloadState.BUSY):
            return
        idle = wl.idle_for()
        if idle >= wl.hard_idle_seconds:
            logger.info("hard idle: stopping workload %s (%.0fs idle)", wl.workload_id, idle)
            await wl.stop()
        elif idle >= wl.soft_idle_seconds:
            logger.info("soft idle: releasing VRAM for %s (%.0fs idle)", wl.workload_id, idle)
            await wl.soft_idle()
            wl.touch()  # reset so soft idle doesn't immediately re-fire

    # ---- shutdown ----

    async def shutdown(self) -> None:
        """Stop all workloads and the idle loop."""
        await self.stop_idle_loop()
        for wl in self._workloads.values():
            try:
                await wl.stop()
            except Exception:
                logger.exception("error stopping workload %s", wl.workload_id)

    def _require(self, workload_id: str) -> Workload:
        wl = self._workloads.get(workload_id)
        if wl is None:
            raise KeyError(f"unknown workload: {workload_id}")
        return wl


class _StoredAsset:
    __slots__ = ("bytes", "mime_type", "created_at")

    def __init__(self, bytes: bytes, mime_type: str, created_at: float) -> None:
        self.bytes = bytes
        self.mime_type = mime_type
        self.created_at = created_at
